Update vw_spectra.py
Do we need this modification ? When I was running this code, I got the error :
```
TypeError: __init__() missing 2 required positional arguments: 'cofm' and 'axis'

```
So, we need to pass the arguments of Spectra to it. Am I right ?